# Copyright 2026 Thales France
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

# Please refer to flows/README.md to add target

"""
Bitstream generation of the CVA6 Intel/Altera FPGA top level (Quartus).

The Intel counterpart of `vivado-fpga-build`, and a separate recipe rather
than an option of it: the two flows share no tool, no top level and no
project format. Quartus drives seven executables where Vivado drives one,
elaborates `cva6_altera` instead of `ariane_xilinx`, and takes its project
from a `.qsf` assembled out of CSV files instead of a TCL script.

Four stages:

- the **Platform Designer systems**, `interconnect` and `system` (which
  carries the HPS), generated by `qsys-script` + `qsys-generate`;
- the **project files**, `.qpf` and `.qsf`, written from the declarative
  CSV files of `corev_apu/altera/` (settings, pin locations, IO standards,
  IP files, search paths) plus the RTL filelist and the SDC constraints;
- the **nine IP cores**, generated by `qsys-script` then by
  `quartus_ipgenerate`;
- the **compilation** itself: `quartus_syn`, `quartus_fit`, `quartus_asm`
  and `quartus_sta`, then `quartus_pfg` for the raw binary file the HPS
  boots from.

The RTL comes from `config/target/<target>/Flist.cva6_altera`, so the file
list is data rather than code, and the CSV files are consumed as they are:
they hold 432 lines of board description that belong to the board, not to
a recipe.

Reports the resource usage and the timing slack as KPIs, checked against
`config/target/<target>/expected_values.yml` when the target carries
baselines for them.
"""

from pathlib import Path
import re
import shutil
import typer

from flows.utils.fpga_board import (
    ALTERA_QSF_OVERRIDDEN,
    ALTERA_IPS,
    ALTERA_QSYS,
    ALTERA_TOP,
    altera_board_params,
)
from flows.utils.manifest import (
    read_manifest,
    require_manifest_option,
    require_prerequisite,
    write_manifest,
)
from flows.utils.recipe_report import RecipeReport
from flows.utils.run_cmd import run_cmd
from flows.utils.autocompletion import AlteraBoard, autocompletion_target
from flows.utils.target_config import (
    read_config_expected_value,
    read_config_or_exit_flist,
    read_config_or_exit_isa,
)

app = typer.Typer()

# Resource deviation tolerance (%) vs
# config/target/<target>/expected_values.yml, like the Xilinx side: the
# fitter is directive driven and moves slightly between two runs.
DIFF_UTILIZATION = 2.0

# Project name of the Quartus flow, and so the basename of every file it
# produces. The same as corev_apu/altera/Makefile: the `.qsf` written
# below is read back by name by every quartus_* executable.
PROJECT = "Example-Project"

# CSV files of `corev_apu/altera/` feeding the `.qsf`, and the assignment
# each line becomes. They describe the board (66 settings, 270 pin
# locations, 74 IO standards...), so they are read as they are.
QSF_FROM_CSV = [
    ("settings.csv", "set_global_assignment -name {}"),
    ("loc_constraints.csv", "set_location_assignment {}"),
    ("io_standard_constraints.csv", "set_instance_assignment -name  {}"),
    ("ip_files.csv", "set_global_assignment -name IP_FILE {}"),
    ("search_paths.csv", "set_global_assignment -name SEARCH_PATH {}"),
]

# Quartus source assignment per file extension
QSF_SOURCE_TYPE = {
    ".vhd": "VHDL_FILE",
    ".v": "VERILOG_FILE",
    ".sv": "SYSTEMVERILOG_FILE",
    ".svh": "SYSTEMVERILOG_FILE",
}

# Compilation stages, in order. Each is a separate executable reading the
# project by name, and each can fail on its own.
QUARTUS_STAGES = [
    ("quartus_syn", "Synthesis", 7200),
    ("quartus_fit", "Fitter", 14400),
    ("quartus_asm", "Assembler", 3600),
]

# `quartus_syn` reports the resource usage in its own report file; the
# fitter refines it. Both are parsed the same way.
RESOURCE_RE = re.compile(
    r";\s*(?P<name>[\w /,()-]+?)\s*;\s*(?P<value>[\d,]+)\s*(?:/\s*[\d,]+\s*\(\s*"
    r"(?P<pct>[\d<>]+)\s*%\s*\))?\s*;"
)

# Worst case slack of `quartus_sta --do_report_timing`
SLACK_RE = re.compile(r"Slack\s*;\s*(-?\d+\.\d+)")


def _qsf_lines(altera_dir, report):
    """
    Return the `.qsf` assignments coming from the CSV board description.

    A missing CSV is fatal: the file holds the pinout or the device
    settings, and a project silently assembled without them would fit to
    the wrong pins.
    """
    lines = []
    for name, template in QSF_FROM_CSV:
        path = altera_dir / name
        if not path.exists():
            report.error_exit(f"Missing board description file: {path}", env=True)
        skipped = 0
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            # The device, the family and the top level come from the board
            # table: see ALTERA_QSF_OVERRIDDEN.
            if line.split(maxsplit=1)[0] in ALTERA_QSF_OVERRIDDEN:
                skipped += 1
                continue
            lines.append(template.format(line))
        if skipped:
            report.info(f"{name}: {skipped} assignment(s) taken from the board table")
        report.info(f"{name}: {len(lines)} assignment(s) so far")
    return lines


def _write_project(out_dir, altera_dir, params, rtl_files, bootrom_sv, report):
    """
    Write the `.qpf` and `.qsf` of the project.

    Written in one go, so a failed run cannot leave a half assembled
    project behind.
    """
    qpf = out_dir / f"{PROJECT}.qpf"
    qsf = out_dir / f"{PROJECT}.qsf"

    qpf.write_text(
        f'PROJECT_REVISION = "{PROJECT}"\n',
        encoding="utf-8",
    )

    lines = [
        "# Generated by ./cook.py quartus-fpga-build -- do not edit.",
        f"set_global_assignment -name TOP_LEVEL_ENTITY {ALTERA_TOP}",
        f"set_global_assignment -name DEVICE {params.device}",
        f'set_global_assignment -name FAMILY "{params.family}"',
    ]
    lines += _qsf_lines(altera_dir, report)

    # RTL, from the filelist plus the generated bootloader. Quartus wants
    # one assignment per file, typed by extension.
    sources = [Path(f) for f in rtl_files] + [Path(bootrom_sv)]
    for src in sources:
        kind = QSF_SOURCE_TYPE.get(src.suffix, "SOURCE_FILE")
        lines.append(f"set_global_assignment -name {kind} {src.as_posix()}")

    # Sources generated by Platform Designer: they only exist once the qsys
    # systems have been elaborated, so they are globbed here and not listed
    # in the filelist.
    generated = []
    for qsys in ALTERA_QSYS:
        for pattern in ("*.v", "*.sv", "*.svh"):
            generated += sorted((out_dir / qsys).rglob(pattern))
    for src in generated:
        kind = QSF_SOURCE_TYPE.get(src.suffix, "SOURCE_FILE")
        lines.append(f"set_global_assignment -name {kind} {src.as_posix()}")
    report.info(f"{len(generated)} file(s) generated by Platform Designer")

    sdc_files = sorted((altera_dir / "constraints").rglob("*.sdc"))
    if not sdc_files:
        report.error_exit(
            f"No SDC constraint in {altera_dir / 'constraints'}", env=True
        )
    for sdc in sdc_files:
        lines.append(f"set_global_assignment -name SDC_FILE {sdc.as_posix()}")

    qsf.write_text("\n".join(lines) + "\n", encoding="utf-8")
    report.info(f"project written: {qsf} ({len(lines)} assignments)")
    return qsf


def _report_resources(report, target, syn_rpt):
    """
    Record the resource usage and check it against the baseline.

    A report that cannot be parsed is a warning, never a failure: the
    bitstream is the deliverable, and a Quartus release changing the layout
    of its tables must not turn a good build red.
    """
    report.step("Resource usage")

    if not syn_rpt.exists():
        report.warning(f"{syn_rpt} missing, skipping resource reporting")
        return

    text = syn_rpt.read_text(encoding="utf-8", errors="replace")
    wanted = {
        "Logic utilization (in ALMs)": "alms",
        "Total registers": "registers",
        "Total block memory bits": "memory_bits",
        "Total DSP Blocks": "dsp",
        "Total pins": "pins",
    }
    found = {}
    for match in RESOURCE_RE.finditer(text):
        name = match.group("name").strip()
        if name in wanted and wanted[name] not in found:
            try:
                found[wanted[name]] = int(match.group("value").replace(",", ""))
            except ValueError:
                continue

    if not found:
        report.warning(f"No resource table found in {syn_rpt}")
        return

    report.metric("Resource usage", found)

    alms = found.get("alms")
    if alms is None:
        report.info("No ALM count in the report, skipping the utilization check")
        return

    report.set_label(f"{alms // 1000} kALMs")
    expected = read_config_expected_value(target, "altera_alms", report)
    report.kpi("altera_alms", alms, unit="ALMs", expected=expected, better="lower")
    for name, unit in (("registers", "FFs"), ("memory_bits", "bits")):
        if name in found:
            report.kpi(f"altera_{name}", found[name], unit=unit, better="lower")

    if expected is None:
        report.info("No expected ALM count available, skipping utilization check")
        return

    diff = (alms - int(expected)) / int(expected) * 100
    details = (
        f"Expected:  {expected} ALMs\n"
        f"Observed:  {alms} ALMs\n"
        f"Deviation: {diff:.2f} %"
    )
    if abs(diff) > DIFF_UTILIZATION:
        report.error(
            f"ALM count deviation limit exceeded (> {DIFF_UTILIZATION} %)\n\n{details}"
        )
    else:
        report.success(f"ALM count within limits.\n\n{details}")


def _report_timing(report, target, sta_rpt):
    """Record the worst slack and fail the build on a violation."""
    report.step("Timing")

    if not sta_rpt.exists():
        report.warning(f"{sta_rpt} missing, skipping timing reporting")
        return

    slacks = [
        float(s)
        for s in SLACK_RE.findall(sta_rpt.read_text(encoding="utf-8", errors="replace"))
    ]
    if not slacks:
        report.warning(f"No slack found in {sta_rpt}, skipping timing check")
        return

    wns = min(slacks)
    expected = read_config_expected_value(target, "altera_slack", report)
    report.kpi("altera_slack", wns, unit="ns", expected=expected, better="higher")
    report.metric("Timing", {"slack": wns, "paths": len(slacks)})

    if wns < 0:
        report.error(f"Timing not met: worst slack {wns} ns")
    else:
        report.success(f"Timing met: worst slack {wns} ns")


# ==========================================================
# RECIPE
# ==========================================================


@app.command()
def quartus_fpga_build(
    target: str = typer.Option(
        ...,
        "--target",
        "-t",
        help="CVA6 user configuration",
        autocompletion=autocompletion_target,
    ),
    board: AlteraBoard = typer.Option(AlteraBoard.agilex7, help="Altera FPGA board"),
    rbf: bool = typer.Option(
        True, help="Also generate the .rbf the HPS boots the fabric from"
    ),
    clean: bool = typer.Option(True, help="Clean working dir before"),
    quiet: bool = typer.Option(
        False, "--quiet", "-q", help="Suppress output (errors only)"
    ),
):
    """
    Quartus FPGA bitstream generation flow
    """
    report = RecipeReport(
        "quartus-fpga-build",
        title="QUARTUS FPGA BUILD",
        context={
            "target": target,
            "board": board,
            "rbf": rbf,
            "clean": clean,
        },
        quiet=quiet,
    )

    repo_dir = Path.cwd()
    altera_dir = repo_dir / "corev_apu" / "altera"
    out_dir = repo_dir / "build" / target / "fpga_altera" / board.value
    report.set_out_dir(out_dir)

    params = altera_board_params(board)
    report.add_context(
        {"device": params.device, "family": params.family, "dev_kit": params.dev_kit},
        table="Board parameters",
    )

    # ==========================================================
    # CHECK PREREQUISITES
    # ==========================================================
    report.step("Check prerequisites")

    # Seven executables, checked up front: a missing one three stages in
    # would waste an hour of fitting.
    tools = ["quartus_sh", "quartus_syn", "quartus_fit", "quartus_asm", "quartus_sta"]
    if rbf:
        tools.append("quartus_pfg")
    tools += ["quartus_ipgenerate", "qsys-script", "qsys-generate"]
    for tool in tools:
        path = shutil.which(tool)
        if path is None:
            report.error_exit(
                f"{tool}: Not found\n"
                f"  The Altera flow needs Quartus Prime Pro in PATH "
                f"(qsys-script and qsys-generate live in its sopc_builder/bin).",
                env=True,
            )
        report.success(f"{tool}: {path}")

    xlen = _xlen(target, report)
    bootrom_dir = repo_dir / "build" / "bootrom" / board.value
    bootrom_sv = bootrom_dir / f"bootrom_{xlen}.sv"
    report.add_context({"xlen": xlen})

    require_prerequisite(
        bootrom_sv,
        f"zero stage bootloader of board '{board.value}' (RV{xlen})",
        f"./cook.py fpga-bootrom -t {target} -c <toolchain> --board {board.value}",
        report=report,
    )
    require_manifest_option(
        read_manifest(bootrom_dir, report),
        "board",
        [board.value],
        f"the bitstream of board '{board.value}' needs a bootloader built for it",
        f"./cook.py fpga-bootrom -t {target} -c <toolchain> --board {board.value}",
        report=report,
        manifest_dir=bootrom_dir,
    )

    # The HPS boots from this preloader image, which is a prebuilt blob of
    # the repository rather than something the flow produces.
    hps_hex = altera_dir / "u-boot-spl-dtb.hex"
    if rbf and not hps_hex.exists():
        report.error_exit(
            f"Missing HPS preloader {hps_hex}\n"
            f"  It is the u-boot SPL the .rbf embeds: pass --no-rbf to stop "
            f"after the .sof, or restore the file.",
            env=True,
        )

    report.success("Prerequisites OK")

    # ==========================================================
    # CLEAN
    # ==========================================================
    report.step("Clean")
    if clean:
        try:
            if out_dir.exists():
                shutil.rmtree(out_dir)
                report.info(f"remove {out_dir}")
        except OSError as e:
            report.error_exit(f"Clean error : {e}", env=True)
    else:
        report.info(f"Skip cleaning {out_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)
    report.info(f"create {out_dir}")

    # ==========================================================
    # PLATFORM DESIGNER SYSTEMS
    # ==========================================================
    # `interconnect` and `system` are Platform Designer systems, not plain
    # IPs: they are elaborated first because the project reads the RTL they
    # generate. The HPS lives in `system`.
    report.step("Generate Platform Designer systems")

    qsys_results = report.metric("Platform Designer")
    for qsys, script in ALTERA_QSYS.items():
        script_path = altera_dir / "ip" / script
        if not script_path.exists():
            report.error_exit(f"Missing qsys script: {script_path}", env=True)
        for stage, cmd in (
            ("script", ["qsys-script", f"--script={script_path}"]),
            (
                "generate",
                [
                    "qsys-generate",
                    f"{qsys}.qsys",
                    f"--quartus-project={altera_dir / 'ip' / Path(script).stem}",
                    "--synthesis",
                ],
            ),
        ):
            run_cmd(
                cmd=cmd,
                report=report,
                cwd=out_dir,
                env=None,
                error_patterns=["^Error|Error:"],
                warning_patterns=["^Warning|Warning:"],
                highlight_patterns=None,
                log_file=out_dir / f"qsys_{qsys}_{stage}.log",
                timeout=3600,
                check=False,
                capture_output=False,
            )
        ok = (out_dir / qsys).is_dir()
        qsys_results.add_row(
            status="pass" if ok else "fail",
            system=qsys,
            state="generated" if ok else "missing",
        )
    report.print_metric(qsys_results)
    if qsys_results.failed:
        report.error_exit("Platform Designer generation failed")

    # ==========================================================
    # PROJECT FILES
    # ==========================================================
    report.step("Write project files")

    rtl_files = read_config_or_exit_flist(
        target, report, filename="Flist.cva6_altera", repo_dir=repo_dir
    )
    report.info(f"{len(rtl_files)} RTL file(s) read from Flist.cva6_altera")

    qsf = _write_project(out_dir, altera_dir, params, rtl_files, bootrom_sv, report)

    # ==========================================================
    # IP CORES
    # ==========================================================
    report.step("Generate IP cores")

    ip_results = report.metric("IP cores")
    for ip_script in ALTERA_IPS:
        script_path = altera_dir / "ip" / ip_script
        if not script_path.exists():
            report.error_exit(f"Missing IP script: {script_path}", env=True)
        run_cmd(
            cmd=["qsys-script", f"--script={script_path}"],
            report=report,
            cwd=out_dir,
            env=None,
            error_patterns=["^Error|Error:"],
            warning_patterns=["^Warning|Warning:"],
            highlight_patterns=None,
            log_file=out_dir / f"ip_{Path(ip_script).stem}.log",
            timeout=1800,
            check=False,
            capture_output=False,
        )
        ip_file = out_dir / f"{Path(ip_script).stem}.ip"
        ip_results.add_row(
            status="pass" if ip_file.exists() else "fail",
            ip=Path(ip_script).stem,
            state="generated" if ip_file.exists() else "missing",
        )
    report.print_metric(ip_results)
    if ip_results.failed:
        report.error_exit("IP core generation failed")

    run_cmd(
        cmd=["quartus_ipgenerate", "--generate_project_ip_files", PROJECT],
        report=report,
        cwd=out_dir,
        env=None,
        error_patterns=["^Error|Error \\("],
        warning_patterns=["^Warning"],
        highlight_patterns=None,
        log_file=out_dir / "ipgenerate.log",
        timeout=3600,
        check=False,
        capture_output=False,
    )
    report.success(f"{len(ALTERA_IPS)} IP core(s) generated")

    # ==========================================================
    # COMPILATION
    # ==========================================================
    # One executable per stage, each reading the project by name. They are
    # run in sequence and the first failure stops the build: fitting a
    # design whose synthesis failed only produces a second error.
    for tool, stage, timeout in QUARTUS_STAGES:
        report.step(stage)
        log_file = out_dir / f"{tool}.log"
        run_cmd(
            cmd=[tool, PROJECT],
            report=report,
            cwd=out_dir,
            env=None,
            error_patterns=["^Error|Error \\("],
            warning_patterns=["^Critical Warning"],
            highlight_patterns=["^Info: Quartus"],
            log_file=log_file,
            timeout=timeout,
            check=False,
            capture_output=False,
        )
        n_err, _ = report.analyze_log(
            log_file,
            name=f"{tool}.log analysis",
            error_patterns=["^Error", "Error \\("],
            warning_patterns=["^Critical Warning"],
            env_patterns=[
                r"(license|licence).*(error|fail|unable|denied|expired)",
                r"unable to checkout",
                r"command not found",
                r"No license",
            ],
            fail_on_error=False,
        )
        if n_err:
            report.error_exit(f"{stage} failed: {n_err} error(s) in {log_file}")
        report.success(f"{stage} completed")

    # Timing analysis: reported but run as its own stage, since its report
    # is what the timing check below reads.
    report.step("Timing analysis")
    run_cmd(
        cmd=["quartus_sta", PROJECT, "--do_report_timing"],
        report=report,
        cwd=out_dir,
        env=None,
        error_patterns=["^Error|Error \\("],
        warning_patterns=["^Critical Warning"],
        highlight_patterns=None,
        log_file=out_dir / "quartus_sta.log",
        timeout=3600,
        check=False,
        capture_output=False,
    )

    sof_files = sorted((out_dir / "output_files").glob("*.sof"))
    if not sof_files:
        report.error_exit(f"Bitstream not generated in {out_dir / 'output_files'}")
    sof_file = sof_files[0]
    report.success(f"Bitstream generated: {sof_file}")

    # ==========================================================
    # HPS BOOT IMAGE
    # ==========================================================
    # The Agilex fabric is configured by the HPS, which needs the raw binary
    # form of the bitstream with the u-boot SPL embedded in it.
    rbf_file = out_dir / "output_files" / "cva6-hps.rbf"
    if rbf:
        report.step("Generate HPS boot image")
        run_cmd(
            cmd=[
                "quartus_pfg",
                "-c",
                str(sof_file),
                str(rbf_file),
                "-o",
                f"hps_path={hps_hex}",
            ],
            report=report,
            cwd=out_dir,
            env=None,
            error_patterns=["^Error|Error \\("],
            warning_patterns=["^Warning"],
            highlight_patterns=None,
            log_file=out_dir / "quartus_pfg.log",
            timeout=1800,
            check=False,
            capture_output=False,
        )
        if rbf_file.exists():
            report.success(f"HPS boot image generated: {rbf_file}")
        else:
            report.error(f"HPS boot image not generated: {rbf_file}")

    # ==========================================================
    # REPORTING
    # ==========================================================
    _report_resources(report, target, out_dir / f"{PROJECT}.syn.rpt")
    _report_timing(report, target, out_dir / f"{PROJECT}.sta.rpt")

    # ==========================================================
    # BUILD MANIFEST
    # ==========================================================
    write_manifest(
        out_dir,
        "quartus-fpga-build",
        {
            "target": target,
            "board": board,
            "xlen": xlen,
            "device": params.device,
            "family": params.family,
            "bootrom_sv": str(bootrom_sv.relative_to(repo_dir)),
            "rbf": rbf,
            "sof": str(sof_file.relative_to(repo_dir)),
        },
        report=report,
    )

    # ==========================================================
    # List
    # ==========================================================
    report.step("Generated files")
    gen_files = [
        sof_file,
        rbf_file,
        qsf,
        out_dir / f"{PROJECT}.qpf",
        out_dir / f"{PROJECT}.syn.rpt",
        out_dir / f"{PROJECT}.fit.rpt",
        out_dir / f"{PROJECT}.asm.rpt",
        out_dir / f"{PROJECT}.sta.rpt",
    ]
    generated = []
    for genfile in gen_files:
        if genfile.exists():
            report.info(f"> {genfile}")
            generated.append(str(genfile.relative_to(repo_dir)))

    # ==========================================================
    # BUILD REPORT
    # ==========================================================
    report.log("Generated files", generated)

    report.end("Completed")


def _xlen(target, report):
    """
    Return the register width the target is built for.

    Read from the ISA the software is compiled with rather than guessed
    from the target name, like the Xilinx recipe does.
    """
    march, _ = read_config_or_exit_isa(target, report)
    if march.startswith("rv64"):
        return 64
    if march.startswith("rv32"):
        return 32
    return report.error_exit(
        f"Cannot tell the register width from march {march!r} of target "
        f"'{target}': expected it to start with rv32 or rv64",
        env=True,
    )
