# Copyright 2026 Thales France
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

# Please refer to flows/README.md to add target

"""
Load a bitstream onto a physical FPGA board (Vivado hardware manager).

Consumes the bitstream of `vivado-fpga-build` and programs the volatile
configuration of the board: the design is lost at power off, which is
what makes it the right step before a boot test. Writing the flash so the
board comes up on its own is a separate operation, from the `.mcs` image.

The board is reached through a `hw_server` the recipe does not start: one
is expected to be running next to the board, and its URL given by
`--hw-server` (default `$HW_SERVER_URL`). The recipe generates the TCL
itself, so a missing URL is an actionable error here rather than a TCL
exception inside Vivado.

Only the boards whose JTAG device name is known can be programmed (see
`flows/utils/fpga_board.py`): the others build fine but are refused here,
with the entry to add.
"""

import os
from pathlib import Path
import shutil
import typer

from flows.utils.fpga_board import FPGA_TOP, board_params
from flows.utils.manifest import (
    read_manifest,
    require_manifest_option,
    require_prerequisite,
    write_manifest,
)
from flows.utils.recipe_report import RecipeReport
from flows.utils.run_cmd import run_cmd
from flows.utils.autocompletion import FpgaBoard, autocompletion_target

app = typer.Typer()


def _program_tcl(hw_server, hw_device, bitstream):
    """Return the Vivado script programming the board."""
    return f"""\
# Generated by ./cook.py vivado-fpga-program -- do not edit.
open_hw_manager
connect_hw_server -url {hw_server}
open_hw_target
current_hw_device [get_hw_devices {hw_device}]
set_property PROGRAM.FILE {{{bitstream.as_posix()}}} [get_hw_devices {hw_device}]
program_hw_devices [get_hw_devices {hw_device}]
refresh_hw_device [lindex [get_hw_devices {hw_device}] 0]
exit
"""


# ==========================================================
# RECIPE
# ==========================================================


@app.command()
def vivado_fpga_program(
    target: str = typer.Option(
        ...,
        "--target",
        "-t",
        help="CVA6 user configuration",
        autocompletion=autocompletion_target,
    ),
    board: FpgaBoard = typer.Option(FpgaBoard.genesys2, help="FPGA board"),
    hw_server: str = typer.Option(
        None,
        "--hw-server",
        help="URL of the hw_server driving the board (default: $HW_SERVER_URL)",
    ),
    bitstream: Path = typer.Option(
        None,
        "--bitstream",
        help="Bitstream to load (default: the vivado-fpga-build output)",
    ),
    vivado_cmd: str = typer.Option(
        "vivado",
        "--vivado-cmd",
        help="Vivado executable (vivado_lab is enough to program a board)",
    ),
    quiet: bool = typer.Option(
        False, "--quiet", "-q", help="Suppress output (errors only)"
    ),
):
    """
    Vivado FPGA board programming flow
    """
    report = RecipeReport(
        "vivado-fpga-program",
        title="VIVADO FPGA PROGRAM",
        context={
            "target": target,
            "board": board,
            "hw_server": hw_server,
            "bitstream": bitstream,
            "vivado_cmd": vivado_cmd,
        },
        quiet=quiet,
    )

    repo_dir = Path.cwd()
    build_dir = repo_dir / "build" / target / "fpga" / board.value
    out_dir = repo_dir / "build" / target / "fpga_program" / board.value
    report.set_out_dir(out_dir)

    params = board_params(board)

    # ==========================================================
    # CHECK PREREQUISITES
    # ==========================================================
    report.step("Check prerequisites")

    # A board is programmable only once its JTAG device name is known:
    # guessing one would fail inside Vivado with nothing actionable.
    if params.hw_device is None:
        report.error_exit(
            f"Board '{board.value}' cannot be programmed by this recipe\n"
            f"  Its JTAG device name is unknown: add `hw_device` to its entry "
            f"in flows/utils/fpga_board.py once it has been checked on the "
            f"board (Vivado hardware manager, get_hw_devices).",
            env=True,
        )

    vivado_path = shutil.which(vivado_cmd)
    if vivado_path is not None:
        report.success(f"{vivado_cmd}: {vivado_path}")
    else:
        report.error_exit(f"{vivado_cmd}: Not found", env=True)

    hw_server = hw_server or os.environ.get("HW_SERVER_URL")
    if not hw_server:
        report.error_exit(
            "No hw_server URL\n"
            "  Pass --hw-server or set $HW_SERVER_URL to the URL of the "
            "hw_server running next to the board (e.g. localhost:3121).",
            env=True,
        )
    report.add_context({"hw_server": hw_server, "hw_device": params.hw_device})

    if bitstream is None:
        bitstream = build_dir / f"{FPGA_TOP}.bit"
        require_prerequisite(
            bitstream,
            f"bitstream of target '{target}' for board '{board.value}'",
            f"./cook.py vivado-fpga-build -t {target} --board {board.value}",
            report=report,
        )
        # The bitstream is board specific: programming a board with the
        # image of another one is refused rather than attempted.
        require_manifest_option(
            read_manifest(build_dir, report),
            "board",
            [board.value],
            f"programming board '{board.value}' needs a bitstream built for it",
            f"./cook.py vivado-fpga-build -t {target} --board {board.value}",
            report=report,
            manifest_dir=build_dir,
        )
    else:
        bitstream = Path(bitstream).resolve()
        require_prerequisite(
            bitstream,
            "bitstream given with --bitstream",
            f"./cook.py vivado-fpga-build -t {target} --board {board.value}",
            report=report,
        )
    report.info(f"bitstream: {bitstream}")

    report.success("Prerequisites OK")

    # ==========================================================
    # CLEAN
    # ==========================================================
    report.step("Clean")
    try:
        if out_dir.exists():
            shutil.rmtree(out_dir)
            report.info(f"remove {out_dir}")
    except OSError as e:
        report.error_exit(f"Clean error : {e}", env=True)

    out_dir.mkdir(parents=True, exist_ok=True)
    report.info(f"create {out_dir}")

    # ==========================================================
    # GENERATE TCL
    # ==========================================================
    report.step("Generate program.tcl")

    tcl = _program_tcl(hw_server, params.hw_device, bitstream)
    script_file = out_dir / "program.tcl"
    script_file.write_text(tcl, encoding="utf-8")
    report.info(f"program.tcl generated at {script_file}")
    report.code(tcl, "tcl")

    # ==========================================================
    # LAUNCH VIVADO
    # ==========================================================
    report.step("Program the board")

    log_file = out_dir / "program.log"

    run_cmd(
        cmd=[vivado_cmd, "-nojournal", "-mode", "batch", "-source", "program.tcl"],
        report=report,
        cwd=out_dir,
        env=None,
        error_patterns=["^ERROR:"],
        warning_patterns=["^WARNING:|^CRITICAL WARNING:"],
        highlight_patterns=None,
        log_file=log_file,
        timeout=1800,
        check=False,
        capture_output=False,
    )

    # A programming failure is an environment problem (board off, busy,
    # cable, hw_server unreachable), not a defect of the design.
    n_err, _ = report.analyze_log(
        log_file,
        name="program.log analysis",
        error_patterns=["^ERROR:"],
        warning_patterns=["^CRITICAL WARNING:"],
        env_patterns=[
            r"(license|licence).*(error|fail|unable|denied|expired)",
            r"unable to connect",
            r"no hardware targets",
            r"command not found",
        ],
        fail_on_error=False,
    )

    if n_err:
        report.error_exit(
            f"Board programming failed: {n_err} error(s) in {log_file}", env=True
        )
    report.success(f"Board programmed: {params.hw_device} @ {hw_server}")
    report.set_label("PROGRAMMED")

    # ==========================================================
    # BUILD MANIFEST
    # ==========================================================
    write_manifest(
        out_dir,
        "vivado-fpga-program",
        {
            "target": target,
            "board": board,
            "hw_server": hw_server,
            "hw_device": params.hw_device,
            "bitstream": str(bitstream),
        },
        report=report,
    )

    # ==========================================================
    # List
    # ==========================================================
    report.step("Generated files")
    generated = []
    for genfile in (script_file, log_file):
        if genfile.exists():
            report.info(f"> {genfile}")
            generated.append(str(genfile.relative_to(repo_dir)))

    # ==========================================================
    # BUILD REPORT
    # ==========================================================
    report.log("Generated files", generated)

    report.end("Completed")
